// <auto-generated />
using System;
using DatVeXemPhim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatVeXemPhim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DatVeXemPhim.Models.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"), 1L, 1);

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComboId");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ComboName = "Combo 1: Bắp lớn + Nước lớn",
                            Description = "1 bắp rang bơ lớn + 1 nước ngọt lớn",
                            IsActive = true,
                            Price = 89000.00m
                        },
                        new
                        {
                            ComboId = 2,
                            ComboName = "Combo 2: Bắp nhỏ + 2 Nước",
                            Description = "1 bắp rang bơ nhỏ + 2 nước ngọt vừa",
                            IsActive = true,
                            Price = 79000.00m
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoyaltyPoint")
                        .HasColumnType("int");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedAt = new DateTime(2026, 7, 9, 15, 25, 8, 577, DateTimeKind.Unspecified),
                            Email = "levanan@gmail.com",
                            FullName = "Lê Văn An",
                            IsActive = true,
                            LoyaltyPoint = 150,
                            MembershipRank = "Thành viên Bạc",
                            PasswordHash = "$2a$hash_cust01",
                            Phone = "0911111111"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 15, 25, 8, 577, DateTimeKind.Unspecified),
                            Email = "phambinh@gmail.com",
                            FullName = "Phạm Thị Bình",
                            IsActive = true,
                            LoyaltyPoint = 0,
                            MembershipRank = "Thành viên mới",
                            PasswordHash = "$2a$hash_cust02",
                            Phone = "0922222222"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreatedAt = new DateTime(2026, 7, 9, 15, 25, 8, 577, DateTimeKind.Unspecified),
                            Email = "hoangchau@gmail.com",
                            FullName = "Hoàng Minh Châu",
                            IsActive = true,
                            LoyaltyPoint = 500,
                            MembershipRank = "Thành viên Vàng",
                            PasswordHash = "$2a$hash_cust03",
                            Phone = "0933333333"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 5,
                            GenreName = "Hài hước"
                        },
                        new
                        {
                            GenreId = 1,
                            GenreName = "Hành động"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Hoạt hình"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Kinh dị"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Tài liệu"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Tình cảm"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Viễn tưởng"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Ethan Hunt và đội IMF đối mặt nhiệm vụ nguy hiểm nhất sự nghiệp trong phần cuối của loạt phim gián điệp hành động kinh điển.",
                            Duration = 170,
                            EndDate = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/mission-impossible-the-final-reckoning.jpg",
                            ReleaseDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "Mission: Impossible – The Final Reckoning"
                        },
                        new
                        {
                            MovieId = 2,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Hai cảnh sát Miami Mike Lowrey và Marcus Burnett phải chạy đua để minh oan cho người chỉ huy quá cố của mình.",
                            Duration = 115,
                            PosterUrl = "/posters/bad-boys-ride-or-die.jpg",
                            ReleaseDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Bad Boys: Ride or Die"
                        },
                        new
                        {
                            MovieId = 3,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một diễn viên đóng thế phải điều tra vụ mất tích của ngôi sao điện ảnh trong lúc cố gắng hàn gắn chuyện tình cũ.",
                            Duration = 126,
                            EndDate = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/the-fall-guy.jpg",
                            ReleaseDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "The Fall Guy"
                        },
                        new
                        {
                            MovieId = 4,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Câu chuyện về tuổi trẻ của Furiosa trong thế giới hậu tận thế khắc nghiệt của vũ trụ Mad Max.",
                            Duration = 148,
                            PosterUrl = "/posters/furiosa-a-mad-max-saga.jpg",
                            ReleaseDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Furiosa: A Mad Max Saga"
                        },
                        new
                        {
                            MovieId = 5,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một nhóm thợ săn bão liều lĩnh đối đầu với những cơn lốc xoáy ngày càng khốc liệt ở vùng Trung Tây nước Mỹ.",
                            Duration = 122,
                            EndDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/twisters.jpg",
                            ReleaseDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "Twisters"
                        },
                        new
                        {
                            MovieId = 6,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Hai người từng có một đêm hẹn hò tuyệt vời rồi trở mặt bất ngờ, buộc phải giả vờ yêu nhau tại một đám cưới ở Úc.",
                            Duration = 103,
                            EndDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/anyone-but-you.jpg",
                            ReleaseDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Anyone but You"
                        },
                        new
                        {
                            MovieId = 7,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một người phụ nữ trẻ phải đối mặt với những lựa chọn khó khăn khi tình yêu và quá khứ đau buồn đan xen.",
                            Duration = 130,
                            EndDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/it-ends-with-us.jpg",
                            ReleaseDate = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "It Ends with Us"
                        },
                        new
                        {
                            MovieId = 8,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một cặp đôi cùng nhau trải qua những cột mốc vui buồn của cuộc sống, tình yêu và bệnh tật.",
                            Duration = 108,
                            EndDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/we-live-in-time.jpg",
                            ReleaseDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "We Live in Time"
                        },
                        new
                        {
                            MovieId = 9,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một người mẹ đơn thân bất ngờ nảy sinh tình cảm với chàng ca sĩ trẻ của một ban nhạc nổi tiếng.",
                            Duration = 115,
                            PosterUrl = "/posters/the-idea-of-you.jpg",
                            ReleaseDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "The Idea of You"
                        },
                        new
                        {
                            MovieId = 10,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Hai người bạn thời thơ ấu tái ngộ sau nhiều năm xa cách, đối diện với những gì có thể đã xảy ra.",
                            Duration = 106,
                            EndDate = new DateTime(2026, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/past-lives.jpg",
                            ReleaseDate = new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Past Lives"
                        },
                        new
                        {
                            MovieId = 11,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một ngôi sao đang lụi tàn sử dụng loại thuốc bí ẩn để tạo ra phiên bản trẻ trung hơn của chính mình, với cái giá khủng khiếp.",
                            Duration = 141,
                            EndDate = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/the-substance.jpg",
                            ReleaseDate = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "The Substance"
                        },
                        new
                        {
                            MovieId = 12,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một ngôi sao nhạc pop phải đối mặt với những sự kiện ngày càng đáng sợ khi thực tại bắt đầu sụp đổ quanh cô.",
                            Duration = 127,
                            PosterUrl = "/posters/smile-2.jpg",
                            ReleaseDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Smile 2"
                        },
                        new
                        {
                            MovieId = 13,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Gã hề sát nhân Art the Clown trở lại gieo rắc kinh hoàng trong đêm Giáng sinh.",
                            Duration = 125,
                            EndDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/terrifier-3.jpg",
                            ReleaseDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Terrifier 3"
                        },
                        new
                        {
                            MovieId = 14,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Ba thế hệ trong gia đình Deetz vô tình mở lại cánh cổng dẫn đến thế giới của hồn ma Beetlejuice.",
                            Duration = 105,
                            PosterUrl = "/posters/beetlejuice-beetlejuice.jpg",
                            ReleaseDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Beetlejuice Beetlejuice"
                        },
                        new
                        {
                            MovieId = 15,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một đặc vụ FBI điều tra loạt án mạng liên quan đến các manh mối huyền bí đầy ám ảnh.",
                            Duration = 101,
                            PosterUrl = "/posters/longlegs.jpg",
                            ReleaseDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Longlegs"
                        },
                        new
                        {
                            MovieId = 16,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Riley bước vào tuổi dậy thì và phải đối mặt với những cảm xúc mới phức tạp hơn trong tâm trí mình.",
                            Duration = 96,
                            PosterUrl = "/posters/inside-out-2.jpg",
                            ReleaseDate = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Inside Out 2"
                        },
                        new
                        {
                            MovieId = 17,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Moana lên đường trong một chuyến hải trình mới đầy thử thách cùng những người bạn cũ và mới.",
                            Duration = 100,
                            PosterUrl = "/posters/moana-2.jpg",
                            ReleaseDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Moana 2"
                        },
                        new
                        {
                            MovieId = 18,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Gru phải bảo vệ gia đình mới của mình trước một kẻ thù cũ đầy nguy hiểm.",
                            Duration = 94,
                            EndDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/despicable-me-4.jpg",
                            ReleaseDate = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Despicable Me 4"
                        },
                        new
                        {
                            MovieId = 19,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một robot bị mắc kẹt trên hòn đảo hoang phải học cách sinh tồn và trở thành người mẹ nuôi của một chú ngỗng con.",
                            Duration = 102,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/the-wild-robot.jpg",
                            ReleaseDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "The Wild Robot"
                        },
                        new
                        {
                            MovieId = 20,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Po phải tìm người kế nhiệm làm Rồng Chiến Binh trong khi đối mặt với một pháp sư biến hình nguy hiểm.",
                            Duration = 94,
                            EndDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/kung-fu-panda-4.jpg",
                            ReleaseDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "Kung Fu Panda 4"
                        },
                        new
                        {
                            MovieId = 21,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Barbie rời khỏi thế giới hoàn hảo của mình để khám phá thế giới thực đầy bất ngờ.",
                            Duration = 114,
                            EndDate = new DateTime(2026, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/barbie.jpg",
                            ReleaseDate = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Barbie"
                        },
                        new
                        {
                            MovieId = 22,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một phụ nữ được thuê để giúp một chàng trai nhút nhát tự tin hơn trước khi vào đại học.",
                            Duration = 103,
                            PosterUrl = "/posters/no-hard-feelings.jpg",
                            ReleaseDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "No Hard Feelings"
                        },
                        new
                        {
                            MovieId = 23,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một nữ tiểu thuyết gia phát hiện cốt truyện trong sách của mình đang trở thành sự thật ngoài đời.",
                            Duration = 139,
                            PosterUrl = "/posters/argylle.jpg",
                            ReleaseDate = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Argylle"
                        },
                        new
                        {
                            MovieId = 24,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một nhóm bạn trẻ phải sống sót qua đêm giao thừa thiên niên kỷ khi máy móc nổi loạn.",
                            Duration = 93,
                            PosterUrl = "/posters/y2k.jpg",
                            ReleaseDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Y2K"
                        },
                        new
                        {
                            MovieId = 25,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một phụ nữ ở độ tuổi 30 bắt đầu hành trình khám phá lại chính bản thân mình.",
                            Duration = 96,
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/am-i-ok.jpg",
                            ReleaseDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Am I OK?"
                        },
                        new
                        {
                            MovieId = 26,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Paul Atreides hợp lực cùng người Fremen trên hành trình trả thù và định đoạt số phận cả vũ trụ.",
                            Duration = 166,
                            EndDate = new DateTime(2026, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/dune-part-two.jpg",
                            ReleaseDate = new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Dune: Part Two"
                        },
                        new
                        {
                            MovieId = 27,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Hai quái vật huyền thoại Godzilla và Kong buộc phải bắt tay chống lại một mối đe dọa ẩn giấu.",
                            Duration = 115,
                            PosterUrl = "/posters/godzilla-x-kong-the-new-empire.jpg",
                            ReleaseDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "Godzilla x Kong: The New Empire"
                        },
                        new
                        {
                            MovieId = 28,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một nhóm người trẻ khai thác trạm vũ trụ bỏ hoang chạm trán sinh vật ngoài hành tinh nguy hiểm bậc nhất vũ trụ.",
                            Duration = 119,
                            EndDate = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/alien-romulus.jpg",
                            ReleaseDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Alien: Romulus"
                        },
                        new
                        {
                            MovieId = 29,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Trong cuộc chiến giữa loài người và trí tuệ nhân tạo, một cựu binh phát hiện vũ khí bí mật mang hình hài đứa trẻ.",
                            Duration = 133,
                            EndDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/the-creator.jpg",
                            ReleaseDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "The Creator"
                        },
                        new
                        {
                            MovieId = 30,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một phụ nữ trẻ được hồi sinh bởi khoa học kỳ lạ và bắt đầu hành trình khám phá thế giới theo cách riêng của mình.",
                            Duration = 141,
                            EndDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/poor-things.jpg",
                            ReleaseDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Poor Things"
                        },
                        new
                        {
                            MovieId = 31,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Ghi lại hành trình leo núi El Capitan không dây bảo hộ đầy mạo hiểm của vận động viên Alex Honnold.",
                            Duration = 100,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/free-solo.jpg",
                            ReleaseDate = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ngừng chiếu",
                            Title = "Free Solo"
                        },
                        new
                        {
                            MovieId = 32,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Một nhà làm phim xây dựng mối quan hệ đặc biệt với một con bạch tuộc hoang dã ngoài khơi Nam Phi.",
                            Duration = 85,
                            PosterUrl = "/posters/my-octopus-teacher.jpg",
                            ReleaseDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "My Octopus Teacher"
                        },
                        new
                        {
                            MovieId = 33,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Bộ phim tài liệu phân tích mối liên hệ giữa chế độ nô lệ và hệ thống nhà tù ở nước Mỹ hiện đại.",
                            Duration = 100,
                            PosterUrl = "/posters/13th.jpg",
                            ReleaseDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Sắp chiếu",
                            Title = "13th"
                        },
                        new
                        {
                            MovieId = 34,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Chân dung về cuộc đời và di sản của Fred Rogers, người dẫn chương trình truyền hình thiếu nhi huyền thoại.",
                            Duration = 94,
                            EndDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/won-t-you-be-my-neighbor.jpg",
                            ReleaseDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Won't You Be My Neighbor?"
                        },
                        new
                        {
                            MovieId = 35,
                            CreatedAt = new DateTime(2026, 7, 12, 17, 13, 55, 597, DateTimeKind.Unspecified),
                            Description = "Câu chuyện có thật đằng sau lễ hội âm nhạc xa hoa sụp đổ thảm hại trên mạng xã hội.",
                            Duration = 97,
                            EndDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterUrl = "/posters/fyre-the-greatest-party-that-never-happened.jpg",
                            ReleaseDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Đang chiếu",
                            Title = "Fyre: The Greatest Party That Never Happened"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 31,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 32,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 34,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 35,
                            GenreId = 7
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("TicketId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReviewId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovieId", "CustomerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 1,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            IsActive = true,
                            RoomName = "Phòng chiếu 1",
                            TotalSeats = 15
                        },
                        new
                        {
                            RoomId = 2,
                            IsActive = true,
                            RoomName = "Phòng chiếu 2",
                            TotalSeats = 8
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"), 1L, 1);

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeatId");

                    b.HasIndex("RoomId", "RowLabel", "ColumnNumber")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            ColumnNumber = 1,
                            RoomId = 1,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 2,
                            ColumnNumber = 2,
                            RoomId = 1,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 3,
                            ColumnNumber = 3,
                            RoomId = 1,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 4,
                            ColumnNumber = 4,
                            RoomId = 1,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 5,
                            ColumnNumber = 5,
                            RoomId = 1,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 6,
                            ColumnNumber = 1,
                            RoomId = 1,
                            RowLabel = "B",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 7,
                            ColumnNumber = 2,
                            RoomId = 1,
                            RowLabel = "B",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 8,
                            ColumnNumber = 3,
                            RoomId = 1,
                            RowLabel = "B",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 9,
                            ColumnNumber = 4,
                            RoomId = 1,
                            RowLabel = "B",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 10,
                            ColumnNumber = 5,
                            RoomId = 1,
                            RowLabel = "B",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 11,
                            ColumnNumber = 1,
                            RoomId = 1,
                            RowLabel = "C",
                            SeatType = "VIP"
                        },
                        new
                        {
                            SeatId = 12,
                            ColumnNumber = 2,
                            RoomId = 1,
                            RowLabel = "C",
                            SeatType = "VIP"
                        },
                        new
                        {
                            SeatId = 13,
                            ColumnNumber = 3,
                            RoomId = 1,
                            RowLabel = "C",
                            SeatType = "VIP"
                        },
                        new
                        {
                            SeatId = 14,
                            ColumnNumber = 4,
                            RoomId = 1,
                            RowLabel = "C",
                            SeatType = "VIP"
                        },
                        new
                        {
                            SeatId = 15,
                            ColumnNumber = 5,
                            RoomId = 1,
                            RowLabel = "C",
                            SeatType = "VIP"
                        },
                        new
                        {
                            SeatId = 16,
                            ColumnNumber = 1,
                            RoomId = 2,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 17,
                            ColumnNumber = 2,
                            RoomId = 2,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 18,
                            ColumnNumber = 3,
                            RoomId = 2,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 19,
                            ColumnNumber = 4,
                            RoomId = 2,
                            RowLabel = "A",
                            SeatType = "Thường"
                        },
                        new
                        {
                            SeatId = 20,
                            ColumnNumber = 1,
                            RoomId = 2,
                            RowLabel = "B",
                            SeatType = "Đôi"
                        },
                        new
                        {
                            SeatId = 21,
                            ColumnNumber = 2,
                            RoomId = 2,
                            RowLabel = "B",
                            SeatType = "Đôi"
                        },
                        new
                        {
                            SeatId = 22,
                            ColumnNumber = 3,
                            RoomId = 2,
                            RowLabel = "B",
                            SeatType = "Đôi"
                        },
                        new
                        {
                            SeatId = 23,
                            ColumnNumber = 4,
                            RoomId = 2,
                            RowLabel = "B",
                            SeatType = "Đôi"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Showtime", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeId"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.ShowtimeSeat", b =>
                {
                    b.Property<int>("ShowtimeSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeSeatId"), 1L, 1);

                    b.Property<DateTime?>("HoldExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShowtimeSeatId");

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowtimeId", "SeatId")
                        .IsUnique();

                    b.ToTable("ShowtimeSeats");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TicketCombo", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("TicketCombos");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TicketDetail", b =>
                {
                    b.Property<int>("TicketDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketDetailId"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShowtimeSeatId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("TicketDetailId");

                    b.HasIndex("ShowtimeSeatId")
                        .IsUnique();

                    b.HasIndex("TicketId");

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 7, 9, 15, 25, 8, 577, DateTimeKind.Unspecified),
                            Email = "admin01@rapphim.vn",
                            FullName = "Nguyễn Văn Quản",
                            IsActive = true,
                            PasswordHash = "$2a$hash_admin01",
                            Phone = "0900000001",
                            RoleId = 2,
                            Username = "admin01"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 15, 25, 8, 577, DateTimeKind.Unspecified),
                            Email = "staff01@rapphim.vn",
                            FullName = "Trần Thị Nhân Viên",
                            IsActive = true,
                            PasswordHash = "$2a$hash_staff01",
                            Phone = "0900000002",
                            RoleId = 1,
                            Username = "staff01"
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("VoucherId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            VoucherId = 1,
                            Code = "SUMMER10",
                            DiscountType = "Phần trăm",
                            DiscountValue = 10.00m,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinOrderAmount = 100000.00m,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 5
                        },
                        new
                        {
                            VoucherId = 2,
                            Code = "GIAM20K",
                            DiscountType = "Số tiền cố định",
                            DiscountValue = 20000.00m,
                            EndDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinOrderAmount = 150000.00m,
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 50,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("DatVeXemPhim.Models.MovieGenre", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Payment", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Review", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Seat", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Showtime", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.ShowtimeSeat", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Showtime", "Showtime")
                        .WithMany("ShowtimeSeats")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ticket", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Showtime");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TicketCombo", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Combo", "Combo")
                        .WithMany("TicketCombos")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Ticket", "Ticket")
                        .WithMany("TicketCombos")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TicketDetail", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.ShowtimeSeat", "ShowtimeSeat")
                        .WithMany()
                        .HasForeignKey("ShowtimeSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.Ticket", "Ticket")
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShowtimeSeat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.User", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Combo", b =>
                {
                    b.Navigation("TicketCombos");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Customer", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("Reviews");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Showtime", b =>
                {
                    b.Navigation("ShowtimeSeats");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ticket", b =>
                {
                    b.Navigation("TicketCombos");

                    b.Navigation("TicketDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
